name: "Build"

on:
  pull_request:
    types: [ "opened", "synchronize", "edited", "reopened" ]
  push:
    branches:
      - master
      - v*.*

env:
  php-extensions: mbstring, intl
  php-extensions-key: v1
  php-tools: "composer:v2"

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.1', '7.2', '7.3', '7.4', '8.0' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP with pecl extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.php-extensions }}
          tools: ${{ env.php-tools }}
          coverage: pcov

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Tests
        run: ./vendor/bin/tester ./tests/cases

      - name: Print failed expectations
        if: ${{ failure() }}
        run: |
          find tests -name \*.actual -exec echo "--- {}" \; -exec cat {} \; -exec echo \; -exec echo \; && \
          find tests -name \*.log -exec echo "--- {}" \; -exec cat {} \; -exec echo \; -exec echo \;
